M48
; DRILL file {KiCad 7.0.8} date Sun Nov 10 19:19:34 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-10T19:19:34+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X0.1262Y-0.2203
X0.3538Y-0.2203
T2
X0.18Y-1.42
X1.24Y-0.18
T0
M30
